---

title: "Presentation"
author: "Hoon"
date: "18/04/2020"
output: 
  xaringan::moon_reader:
    css: ["default", "sydney.css", "sydney-fonts.css"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
    seal: false
---

```{r setup, include = FALSE}
library(tidyverse)
```
class: segue-red

# KTPT Design Schedule

### A presentation by Group 20  

---
class: sydney-red, center, top
background-image: url(USydLogo.svg)
background-position: 95% 5%
background-size: 15%

## .white[ Table of Contents]

.left[
1. The issue at hand

2. Introducing the KTPT

3. Inner workings of the KTPT

4. UI plans

5. Evaluation metrics to be used.

6. Timeline and Process

]

---
class: sydney-red, center, top
background-image: url(USydLogo.svg)
background-position: 95% 5%
background-size: 15%

## .white[The issue at hand]

.left[
- Short term graft success (less than one year) in Australia is 90%, one of the highest in the world.
- However in the long term, proportion of patients who develops graft rejection is high
]

---
class: sydney-blue, center, top
background-image: url(USydLogo.svg)
background-position: 95% 5%
background-size: 15%

## .white[Introducing the KTPT]

.left[
The Kidney Tranplantation Prediction Tool is being designed to aid doctors and health professionals in predicting the long term Kidney graft rejection.
The KTPT has two components:
1. Eplet and HLA mismatch prediction Tool     
The first component utilizes several metrics derived from the survival analysis of Eplet, HLA and DSA data.
    
2. Gene Expression prediction Tool    
The second component utilizes microanalysis of gene expression data.
]

---

class: sydney-blue, center, top
background-image: url(USydLogo.svg)
background-position: 95% 5%
background-size: 15%

## .white[Inner workings of the KTPT]

.left[
#### .white[Metrics to investigate with the Eplet, HLA and DSA data.]

- Model of DSA activation and time for class 1 eplets
- Model of DSA activation and time for class 2 eplets
- Model of predicting any type of acute rejection utilising core eplet data and HLA mismatches 
- Model of predicting any type of acute rejection utilising core eplet data and eplet mismatches 
- Model of ACR OR ACM time and True Or False For observation for any time of acute rejection

]

---
class: sydney-blue, center, top
background-image: url(USydLogo.svg)
background-position: 95% 5%
background-size: 15%

## .white[Inner workings of the KTPT]

.left[
#### .white[Proposed Models to Investigate the Metrics]

*Cross Validated Random Forest survival*
- By applying the rfs package

*Cross validated Lasso Regression Model*
- By applying the cv.glmnet function the glmnet package

*Cross validated Logistic Regression Model*
- By applying the cv.glmnet function from the glmnet package

*Cox Regressional model utilising Principal component analysis*
- By applying the prcomp and coxph function from the survival package
]

---

class: sydney-blue, center, top
background-image: url(USydLogo.svg)
background-position: 95% 5%
background-size: 15%

## .white[Inner workings of the KTPT]

.left[
#### .white[Main Metric utilising the Gene Expression dataset]

- Model of Acute Rejection utilising gene expression data

#### .white[Proposed Models to Investigate the Metric]    

*Support vector Machines*
- using the e1071 package

*Random Forest*
- using the Random Forest package

*k-Nearest Neighbors*
- using the knn function

]

---

class: sydney-blue, center, top
background-image: url(USydLogo.svg)
background-position: 95% 5%
background-size: 15%

## .white[Inner workings of the KTPT]

.left[#### .white[Our Expectations of the Final Models and it's limitations]    

*Logsitic classification models*
.green[- Easily interpretable predicted probabilities]
.red[- Thresholding]

*PCA*
.green[- Efficient Predictions with less bias and overfitting.]
.red[- Information loss]
]

---

class: sydney-blue, center, top
background-image: url(USydLogo.svg)
background-position: 95% 5%
background-size: 15%

## .white[Inner workings of the KTPT]
.left[#### .white[Our Expectations of the Final Models and it's limitations]    

*Survival Analysis models*

.green[- Hazard Ratios provide risk relative to data already at hand]
.red[- susceptible to garbage information]
.black[- Relevant graphics]

]

---
class: sydney-yellow, center, top
background-image: url(USydLogo.svg), url(Screen_Shot.png)
background-position: 95% 5%, 50% 50%
background-size: 15%, 90%


## .black[User Interface of the KTPT]


---
class: sydney-yellow, center, top
background-image: url(USydLogo.svg)
background-position: 95% 5%
background-size: 15%


## .black[Evaluation metrics]

- Ensure relevant datasets fit the assumptions of the models being used to determine the metrics
- The best survival analysis model will be selected by the use of the C-Index, a generalisation of the area under the AUC.
- The best classification model will be determined by the use of standard metrics.
---
class: sydney-yellow, center, top
background-image: url(USydLogo.svg)
background-position: 95% 5%
background-size: 15%

## .black[Timeline and Process]

---